### ISSUE TITLE
Cache handling for http request

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Web_Kernel#16]
The http needs cache handling in the core.

Was working on a weekend project http://ghdocs.herokuapp.com/ . Heroku don't have a write to file system.

So it suggests the response to be cached via http https://devcenter.heroku.com/articles/read-only-filesystem .

**Comment by pmjones** [comment]
I disagree. Any caching that "needs" to be handled can be taken care of outside the kernel.

**Comment by harikt** [comment]
That means the person who develop need to take care of it ?

**Comment by pmjones** [comment]
Yes. The kernel is _intentionally_ very, very limited. It does only the bare minimum.
