### ISSUE TITLE
Router should be released and make use of generateRaw

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Web_Kernel#17]
https://github.com/auraphp/Aura.Web_Kernel/blob/2.0.0/composer.json

https://github.com/auraphp/Aura.Router/pull/63

@pmjones urgent release of Aura.Router with changes to composer.json for the fix needed.

**Comment by pmjones** [comment]
Thanks -- working on it now.

**Comment by pmjones** [comment]
Done.

**Comment by harikt** [comment]
Thank you. Didn't thought releasing the router itself will fix the issue :+1:  .
