### ISSUE TITLE
Router and Dispatcher

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Web_Kernel#18]
Hi Guys, 

Yesterday Jakey69 was mentioning about so many configuration. I did thought a bit about it, and wonder whether this is possible.

``` php
$router = $di->get('aura/web-kernel:router');

$router->add('aura.blog.browse', '/blog{/page}')
    ->setValues(array(
        'action' => 'aura.blog.browse',
        'page' => 1
    ))
    ->addTokens(array(
        'page'  => '\d+',
    ));

$dispatcher = $di->get('aura/web-kernel:dispatcher');

$dispatcher->setObject(
    'aura.blog.browse',
    $di->lazyNew('Aura\Blog\Web\Action\BlogBrowseAction')
);
```

Can we add a bridge or something like that which have the router and dispatcher so we only need to take one service and add it. Not sure what I should call the service Eg : 

``` php
$router_dispatcher = $di->get('aura/web-kernel:router_dispatcher');

$router_dispatcher->add('aura.blog.browse', '/blog{/page}')
    ->setValues(array(
        'action' => $di->lazyNew('Aura\Blog\Web\Action\BlogBrowseAction'),
        'page' => 1
    ))
    ->addTokens(array(
        'page'  => '\d+',
    ));
```

See we removed the dispatcher itself. But in the background we can add to the dispatcher itself. Your thoughts ?

**Comment by harikt** [comment]
Ping @avaq , @pmjones : for you guys were mainly at the time and have also discussed with him.

**Comment by Avaq** [comment]
This is already possible. There are two ways to have a shorter route-to-dispatcher notation:

**1)** This is your example. What will happen is that the values will be given to the dispatcher, which resolves the lazy because it has recursive resolving of callables built into its `dispatch`-method:

``` php
$router = $di->get('aura/web-kernel:router');
$router->add('blog', '/blog{/page}')
  ->setValues(['page' => 1, 'action' => $di->lazyNew('MyBlogAction')]);
$router->add('gallery', '/gallery{/page}')
  ->setValues(['page' => 1, 'action' => $di->lazyNew('MyGalleryAction')]);
```

**2)** Defining a single route and setting the objects on your dispatcher:

``` php
$router = $di->get('aura/web-kernel:router');
$router->add(null, '/{action}{/page}');

$dispatcher = $di->get('aura/web-kernel:dispatcher');
$dispatcher->setObject('blog', $di->lazyNew('MyBlogAction'));
$dispatcher->setObject('gallery', $di->lazyNew('MyGalleryAction'));
```

**Comment by harikt** [comment]
Hey @Avaq , 

Nice . I forgot I did mentioned the same on the irc... Thank you for the inputs.
