### ISSUE TITLE
WebKernelTest not found issue

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Web_Kernel#19]
composer.json have "web-kernel-test": "Aura\Web_Kernel\_Config\WebKernelTest" . But it is used on tests/kernel/config which is not added to autoload or autoload-dev .

In that case when having a `web-kernel-test` mode breaks for not loading the file even if it is not needed.

Do you think we can add to autoload-dev or we may want to move to config of the root.

**Comment by pmjones** [comment]
I think this has been resolved with the newest release. Let me know if you still see problems.
