### ISSUE TITLE
Handling the priority in bundles.

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Web_Kernel#20]
Aura. Blog have sidebar attached to the TemplateRegistry map  https://github.com/harikt/Aura.Blog/blob/cbd991d1c039c1dae67b4808d11d4d14738cee81/config/Common.php#L69

``` php
$di->params['Aura\View\TemplateRegistry']['map']['sidebar'] = dirname(__DIR__) . '/src/Web/Responder/layouts/sidebar.php';
```

My idea is to replace the sidebar with a different one on another bundle. In this case we don't know what order the di is taking, and overwriting the one will happen.

The exact use is to render sidebar in cocoframework example using aura/blog example with the sidebar .

Any other ideas are welcome!

Thanks

**Comment by pmjones** [comment]
Perhaps the right thing to do here is not to assign the value in configuration, but in a class method; e.g. in a responder that uses the template object.

**Comment by harikt** [comment]
@pmjones no for there is no responder for it.

Eg : see how Aura.Blog is integrated inside the Cocoframework.Example . You will understand what I was trying to do.

I am trying to change the sidebar of Aura.Blog with the one on Cocoframework.Example . 

https://github.com/cocoframework/Cocoframework.Example

**Comment by harikt** [comment]
Closing for this could not be done. We don't know which bundle config is getting loaded first. If there is some sort of priority also it may help ( in that case we may need to sort with priority in project kernel ) .
