### ISSUE TITLE
Header method has only one param

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Web_Kernel#6]
Bug reported by kenji_s on twitter  https://twitter.com/kenji_s/status/431184806588977152

> @pmjones hi, https://github.com/auraphp/Aura.Web_Kernel/blob/develop-2/src/WebKernelResponder.php#L35  header() method has only one param.

**Comment by pmjones** [comment]
I think this has been resolved; please let me know if you discover otherwise.

**Comment by harikt** [comment]
You merged the PR, so it should :-) .
