### ISSUE TITLE
Signal inside WebKernel

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Web_Kernel#8]
As discusses earlier ( we talked about Middleware also ) I am thinking of having a signal on and after each 

https://github.com/auraphp/Aura.Web_Kernel/blob/reduced/src/WebKernel.php#L50-L52

``` php
$this->signal->send('before_route');
$this->router->__invoke();
$this->signal->send('before_dispatch');
$this->dispatcher->__invoke();
$this->signal->send('before_respond');
$this->responder->__invoke();
```

I also wish if we can get the value after the dispatcher is invoked. 

``` php
$this->dispatcher->__invoke();
```

The idea is returning some value from controller than setting the response from the controller.

``` php
return array('some_view_value' => 'Hello View');
```

and in the before respond send the data, which is got from the controller back. (response, request will also be send). So if we have injected a view we can render and set the content in response.

**Comment by harikt** [comment]
Hey @pmjones , 
I am coming here again with request to bring signal back.

One example is when using a profiler. We need to inject / have a callback on each page  which can inject something. So please bring the Signal back.

**Comment by pmjones** [comment]
If a profiler goes on a page, then it can go in the Action. Alternatively, the profiler can be loaded before the front controller, and then called in the Renderer. There are plenty of ways to do that without signals.

**Comment by pmjones** [comment]
The short version is that Signals don't have to be in the _Kernel_. They may go elsewhere.

**Comment by harikt** [comment]
@pmjones why I think is if it goes into Action either we need to extend that action always. Or add a call to some functional / signal always.

Eg : LoginAction doesn't extend anything. You need to add signal manager and call the signal handler. 

You may say to extend that action, but may be if someone didn't then it is lost. Or may be you have a different / better idea than this.

**Comment by pmjones** [comment]
If you want to write an action that accepts a Signal injection, and emits signals to it, that's fine. No need to extend anything if you don't want to.

**Comment by pmjones** [comment]
Basically, I have zero desire to add any more separated interfaces than are absolutely necessary, and maybe not even the ones that _are_ absolutely necessary. After having used them, consider me prejudiced against them except when there is demonstrably (in code, with examples) no other alternative.

**Comment by harikt** [comment]
One more time let me try : @pmjones the idea is say in development you need to inject something. And on production you don't. In that case either we need to extend the `Action` which has a signal injected always or always inject a signal inside and call the handlers.

May be profiling you may say is one page at a time and is not a case to. 

``` php
class SomeAction
{
    public function __construct($signal, ...$params)
    {
        $this->signal = $signal;
    }

    public function __invoke()
    {
        $this->signal->send('before_action');
        // action stuffs
        $this->signal->send('after_action');
    }
}
```

See in all actions I need to add these lines even I extend a class only to add a constructor or setter for signal.

But if that is in kernel it would have helped. No one knows which route was called, or if they need to alter / check something. I know you mentioned it should be in action to check for ACL. Still one more time.

**Comment by pmjones** [comment]
The solution to "inject something in dev and nothing in production" is to always inject it, but a different variation. Cf. the Monolog NullLogger -- if you don't want logging to occur, inject that instead of a real logger.

**Comment by harikt** [comment]
I am sorry I could not impress you much on this :) .
